# Generated by Django 5.1.3 on 2026-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mensagem_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='tag',
            field=models.CharField(default='Geral', max_length=80),
        ),
    ]
